language: node_js
node_js:
   - "12"

cache : npm

# cache:
#   directories:
#   - "$HOME/.composer/cache"

install:
   - npm install

before_script: true

script:
   - "./node_modules/.bin/jshint"
   - "./node_modules/.bin/retire"
   - "./node_modules/.bin/twly"

after_script: true

deploy:
   provider: heroku
   api_key:
    secure: 6dfdc08f-f2eb-4dbb-8493-d551cf5491d5
   app: app-travis
   on:
    repo: artmoovizweb/Evaluation_Travis_applicationJS
    branch: master